### ISSUE TITLE
Director/Envoy imperfections 

### ISSUE THREAD

**Issue by alexey-gruzdev** [intel/openfl#128]
- [x] **Docs for Director/Envoy** - @igor-davidyuk - https://github.com/intel/openfl/pull/154
- [x] [Redesign stream metrics](https://github.com/intel/openfl/pull/104#discussion_r678522308)  - @igor-davidyuk  - https://github.com/intel/openfl/pull/135
- [x] [Create structure for metric_origin, task_name, metric_name, metric_value, round_ ](https://github.com/intel/openfl/pull/104#discussion_r676791294) - @igor-davidyuk  - https://github.com/intel/openfl/pull/135
- [x] [Get trained model API - return dict](https://github.com/intel/openfl/pull/104#discussion_r678504250) - @igor-davidyuk - https://github.com/intel/openfl/pull/135
- [x] [Return single Tensor dict from function](https://github.com/intel/openfl/pull/104#discussion_r679053518) - @igor-davidyuk - https://github.com/intel/openfl/pull/135
- [x] [Rewrite test](https://github.com/intel/openfl/pull/137/files#diff-5abae20cc95f9239f7d23a1ad0712d79f4ff54e15096919d2a32b4bc4c2e66c3R41) - @igor-davidyuk - https://github.com/intel/openfl/pull/135
- [x] [Timeout settings](https://github.com/intel/openfl/pull/104#commitcomment-53831115) - @aleksandr-mokrov - https://github.com/intel/openfl/pull/153
- [x] [Collaborator working dir?](https://github.com/intel/openfl/pull/104#discussion_r676762368) - @aleksandr-mokrov  -https://github.com/intel/openfl/pull/140 - not now
- [x] [Change order of context manager and move function definition](https://github.com/intel/openfl/pull/104#discussion_r676943611) - @dmitryagapov - https://github.com/intel/openfl/pull/136
- [x] [Save archive to file instead of loading to memory](https://github.com/intel/openfl/pull/104#discussion_r676780872) - @aleksandr-mokrov  - https://github.com/intel/openfl/pull/141
- [x] [Unify workspace import procedure](https://github.com/intel/openfl/pull/104#discussion_r649729356)  - @aleksandr-mokrov - https://github.com/intel/openfl/pull/148
- [x] [Decorator instead of validate_caller?](https://github.com/intel/openfl/pull/104#discussion_r676795411) - @dmitryagapov - https://github.com/intel/openfl/pull/166
- [x] [Change sha384 checking over all codebase](https://github.com/intel/openfl/pull/104#discussion_r678387590) - @itrushkin #134 
- [x] [Refactor getting binary files for step-ca](https://github.com/intel/openfl/pull/104#discussion_r678468452) - @dmitryagapov - https://github.com/intel/openfl/pull/144
- [x] [Create a variable for `step_config, cert, pass_file, config`](https://github.com/intel/openfl/pull/104#discussion_r679019408) - @dmitryagapov - https://github.com/intel/openfl/pull/150
- [x] [If tls: instead of disable_tls over all codebase](https://github.com/intel/openfl/pull/104#discussion_r679044923) - @aleksandr-mokrov - https://github.com/intel/openfl/pull/133
- [x] [Common naming for certs over all codebase](https://github.com/intel/openfl/pull/104#discussion_r676812104) - @dmitryagapov - https://github.com/intel/openfl/pull/146
- [x] [Return error codes instead of single status in GRPC](https://github.com/intel/openfl/pull/104#discussion_r676793851) - @dmitryagapov - https://github.com/intel/openfl/pull/143 - changes not needed
- [x] Set default path for step-ca/step CLI binary and certificates (i.e. `~/.local/workspace/`) with standard naming convention ('director.crt', 'envoy_one.crt', 'envoy_two.crt', etc.) so long living entities can start without always providing path for root_cert, cert, and private_key (defaults can still be overridden) - separated issue was created https://github.com/intel/openfl/issues/161
- [x] [Consistent director_uri flags for director and envoy](https://github.com/intel/openfl/issues/139) - @aleksandr-mokrov - https://github.com/intel/openfl/pull/149
- [x] [Make error logs in director / envoy more informative](https://github.com/intel/openfl/issues/142) - @aleksandr-mokrov - https://github.com/intel/openfl/pull/157
- [x] [Do not pass in step CA password from command line]
 (https://github.com/intel/openfl/blob/develop/openfl/interface/pki.py#L56) - @aleksandr-mokrov - https://github.com/intel/openfl/pull/155
