### ISSUE TITLE
Add flake8 plugins

### ISSUE THREAD

**Issue by dmitryagapov** [intel/openfl#310]
- [ ] flake8 plugin to check that all function parameters have annotation
  - [ ] components: #377
  - [x] cryptography #388 
  - [x] databases #380 
  - [ ] federated
    - [ ] data #390 
    - [ ] plan #391
    - [ ] task #393 
  - [ ] interface
  - [ ] native
  - [ ] pipelines
  - [ ] plugins
  - [ ] protocols
  - [ ] transport
  - [ ] utilities
  - [ ] openfl-tutorials (optional) #383
  - [x] openfl-workspace (optional) #381 
  - [ ] final check
- [x] flake8 plugin to check that all files have correct copyrights: #370 
- [ ] flake8 plugin to check trailing comma [flake8-commas](https://pypi.org/project/flake8-commas/)

**Comment by MasterSkepticista** [comment]
Closing due to inactivity. OpenFL now uses an updated linting and formatting tool.
